package glog_test

import (
	"bytes"
	awesomeProject2 "github.com/blankalmasry/glog-wrapper"
	"github.com/golang/glog"
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

func TestMyCode(t *testing.T) {
	// capture the output generated by your code during the test
	var buf bytes.Buffer
	glog.SetOutput(&buf)
	log = awesomeProject2.logger
	defer glog.SetOutput(os.Stderr)
	// call your code using the GlogAdapter logger
	wrapper.logger.Logf(LogLevelInfo, "info message")
	wrapper.logger.Logf(LogLevelWarn, "warning message")
	wrapper.logger.Logf(LogLevelError, "error message")

	// assert that the expected log messages were generated
	output := buf.String()
	assert.Contains(t, output, "info message")
	assert.Contains(t, output, "warning message")
	assert.Contains(t, output, "error message")
}
